# Generated by Django 4.1.7 on 2023-02-17 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StripeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=300)),
                ('price', models.CharField(max_length=300)),
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stripe', to='main.item')),
            ],
        ),
    ]
