# Generated by Django 4.1.7 on 2023-02-18 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_discount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tax',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('inclusive', models.BooleanField()),
                ('percentage', models.FloatField()),
                ('stripe', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
