# Generated by Django 4.1.7 on 2023-02-18 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_item_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='currency',
            field=models.CharField(default='usd', max_length=200),
        ),
        migrations.AlterField(
            model_name='stripeitem',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stripe', to='main.item'),
        ),
    ]
