# Generated by Django 4.1.7 on 2023-02-18 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_item_currency_alter_stripeitem_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stripeitem',
            name='item',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stripe', to='main.item'),
        ),
    ]
